### ISSUE TITLE
Accept transform file as node module name

### ISSUE THREAD

**Issue by AndersDJohnson** [facebook/jscodeshift#233] opened 2017-12-27 00:02 UTC
It would be great to be able to run transforms from node modules using only the npm identifier, e.g., `some-module` to run the file in the `node_modules/some-module/package.json` `main` field as a codemod transform, and/or node module resolution logic, e.g., `some-module/some-file` to run `node_modules/some-module/some-file.js` as a codemod transform. Using full node module resolution logic would allow referring to locally or globally installed transforms. This would help the ecosystem by making it easy to publish and consume code transforms via npm.

**Comment by brysgo** [comment] 2017-12-27 00:56
I created something to solve a similar problem a while ago. It is called jscodemigrate.

Basically wraps jscodeshift with a migration API that I had imagined being something akin to a modular prettier with higher level, framework specific opinions.

**Comment by DrewML** [comment] 2017-12-27 21:39
Think we can consider this a duplicate of https://github.com/facebook/jscodeshift/issues/126. @AndersDJohnson want to continue the discussion there?

**Closed** 2017-12-28 22:09 UTC
